model: yolov5s-cls.pt
data: /Users/william/dev/yolo5-wildlife-classifier/wildlife_yolo_dataset
epochs: 50
batch_size: 64
imgsz: 224
nosave: false
cache: null
device: ''
workers: 8
project: wildlife_species_classifier
name: baseline_run_01
exist_ok: false
pretrained: true
optimizer: Adam
lr0: 0.001
decay: 5.0e-05
label_smoothing: 0.1
cutoff: null
dropout: null
verbose: false
seed: 0
local_rank: -1
save_dir: wildlife_species_classifier/baseline_run_012
